#! /Users/xhalc/python-venv/.venv/bin/python3

# 'diashow_play.py'
# takes a JSON list of absolute image paths,
# e.g. generated by 'diashow_mdfind.py'
# displays the images in a PyQt6 window
# you need to 'pip install PyQt6'

from __future__ import annotations
import sys, pathlib, tomllib, argparse, json
from dataclasses import dataclass
from typing import List

from PyQt6.QtCore import Qt
from PyQt6.QtGui import (
    QKeyEvent,
    QPixmap,
    QImage,
    QPainter,
    QColor,
    QPalette,
)
from PyQt6.QtWidgets import (
    QApplication,
    QLabel,
    QMainWindow,
    QMessageBox,
    QSizePolicy,
)


# ANSI SGR formatting sequences
def ft(code) -> str:
    return '\x1b[' + str(code) + 'm'
def fc(code) -> str:
    return ft('38;5;' + str(code))

# formatted warnings
def warn(msg):
    print(fc(196) + str(msg) + ft(0), file=sys.stderr)

# read configuration file
def read_configuration(my_path: pathlib.Path) -> dict:
    config_path = my_path.with_suffix('.toml')
    try:
        with open(config_path, 'rb') as f:
            return tomllib.load(f)
    except Exception as e:
        warn('TOML error: ' + str(e))
        return {}

# parse arguments
def get_arguments(my_name: str) -> argparse.Namespace:
    parser = argparse.ArgumentParser(prog=my_name)
    parser.add_argument('parameter',
                        type=str,
                        help='parameter help')
    parser.add_argument('--option',
                        action='store_true',
                        required=False,
                        help='option help')
    return parser.parse_args()

# Slides class
@dataclass(frozen=True)
class Slides:
    paths: List[pathlib.Path]

    @staticmethod
    def load_from_file(path: pathlib.Path) -> 'Slides':
        if not path.exists():
            raise FileNotFoundError(f'file not found: {path}')
        try:
            data = json.loads(path.read_text(encoding='utf-8'))
        except json.JSONDecodeError as e:
            raise ValueError(f'broken json in {path}: {e}') from e
        if not isinstance(data, list) or not all(isinstance(x, str) for x in data):
            raise ValueError(f'{path} is not a list of strings')
        paths = [pathlib.Path(p) for p in data]
        if not paths:
            raise ValueError(f'{path} is empty')
        return Slides(paths=paths)

# SlideshowWindow class
class SlideshowWindow(QMainWindow):
    def __init__(self, slides: Slides) -> None:
        super().__init__()
        self.setWindowTitle('Diashow')
        self._slides = slides
        self._index = 0
        self._label = QLabel(alignment=Qt.AlignmentFlag.AlignCenter) # type: ignore
        self._label.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        #self._label.setAutoFillBackground(True)
        #self._label.setStyleSheet('background: white;')
        self.setCentralWidget(self._label)
        self._pixmap_original: QPixmap | None = None
        self._load_current_image()

    def _load_current_image(self) -> None:
        path = self._slides.paths[self._index]
        pix = QPixmap(str(path))
        if pix.isNull():
            QMessageBox.warning(self, 'error:', f'could not load image:\n{path}')
            self._pixmap_original = None
            self._label.setText(f'error while loading:\n{path}')
            return
        img = pix.toImage().convertToFormat(QImage.Format.Format_ARGB32)
        bg = QImage(img.size(), QImage.Format.Format_ARGB32)
        bg.fill(Qt.GlobalColor.white)
        painter = QPainter(bg)
        painter.drawImage(0, 0, img)
        painter.end()
        self._pixmap_original = QPixmap.fromImage(bg)
        self._update_view()

    def _update_view(self) -> None:
        if self._pixmap_original is None:
            return
        target_size = self._label.size()
        scaled = self._pixmap_original.scaled(
            target_size,
            Qt.AspectRatioMode.KeepAspectRatio,
            Qt.TransformationMode.SmoothTransformation,
        )
        self._label.setPixmap(scaled)
        total = len(self._slides.paths)
        current = self._index + 1
        self.setWindowTitle(f'Diashow {current}/{total}  {self._slides.paths[self._index]}')

    def resizeEvent(self, event) -> None: # type: ignore
        super().resizeEvent(event)
        self._update_view()

    # left and right keys to move through the list of images
    def keyPressEvent(self, event: QKeyEvent) -> None: # type: ignore
        key = event.key()
        if key == Qt.Key.Key_Right:
            self._next()
        elif key == Qt.Key.Key_Left:
            self._prev()
        else:
            super().keyPressEvent(event)

    def _next(self) -> None:
        if self._index < len(self._slides.paths) - 1:
            self._index += 1
            self._load_current_image()

    def _prev(self) -> None:
        if self._index > 0:
            self._index -= 1
            self._load_current_image()

# dark theme
def apply_dark_theme(app: QApplication) -> None:
    app.setStyle("Fusion")
    p = QPalette()
    p.setColor(QPalette.ColorRole.Window, QColor(30, 30, 30))
    p.setColor(QPalette.ColorRole.WindowText, QColor(220, 220, 220))
    p.setColor(QPalette.ColorRole.Base, QColor(25, 25, 25))
    p.setColor(QPalette.ColorRole.AlternateBase, QColor(35, 35, 35))
    p.setColor(QPalette.ColorRole.ToolTipBase, QColor(220, 220, 220))
    p.setColor(QPalette.ColorRole.ToolTipText, QColor(220, 220, 220))
    p.setColor(QPalette.ColorRole.Text, QColor(220, 220, 220))
    p.setColor(QPalette.ColorRole.Button, QColor(45, 45, 45))
    p.setColor(QPalette.ColorRole.ButtonText, QColor(220, 220, 220))
    p.setColor(QPalette.ColorRole.BrightText, QColor(255, 0, 0))
    p.setColor(QPalette.ColorRole.Link, QColor(80, 160, 255))
    p.setColor(QPalette.ColorRole.Highlight, QColor(80, 160, 255))
    p.setColor(QPalette.ColorRole.HighlightedText, QColor(0, 0, 0))
    app.setPalette(p)

# main program
def main() -> int:
    # my path
    my_path = pathlib.Path(__file__)
    my_dir  = my_path.parent
    my_name = my_path.name

    config = read_configuration(my_path)

    #arguments = get_arguments(my_name)

    try:
        slides = Slides.load_from_file(config['slidesfile'])
        if not slides:
            warn('no slides in: ' + str(config['slidesfile']))
    except Exception as e:
        print(f'error: {e}', file=sys.stderr)
        return 1

    app = QApplication(sys.argv)
    apply_dark_theme(app)
    win = SlideshowWindow(slides)
    #win.resize(1280, 720)
    #win.showMaximized()
    win.showFullScreen()
    win.show()
    return app.exec()

if __name__ == '__main__':
    sys.exit(main())
